import { StyleSheet } from "react-native";

export const editorStyles = StyleSheet.create({
  editor: { gap: 18, width: "100%" },
  section: { gap: 10 },
  recommendationSection: {
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingBottom: 12,
    gap: 8,
  },
  sectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  headingLabel: { flexDirection: "row", alignItems: "center", gap: 6 },
  recommendButton: {
    minHeight: 48,
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  sectionTitle: { fontSize: 16, fontWeight: "600", lineHeight: 24 },
  body: { fontSize: 14, lineHeight: 22, flexShrink: 1 },
  caption: { fontSize: 13, lineHeight: 19 },
  notice: { borderWidth: 1, borderRadius: 14, padding: 14, gap: 6 },
  recommendationState: { flexDirection: "row", alignItems: "center", gap: 9 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  recommendationChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minHeight: 48,
    maxWidth: "100%",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderRadius: 24,
  },
  selectedChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    minHeight: 48,
    maxWidth: "100%",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 24,
  },
  chipText: { fontSize: 14, lineHeight: 21, fontWeight: "500", flexShrink: 1 },
  tagInputRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  tagInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 12,
    fontSize: 14,
    lineHeight: 22,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  addButton: {
    minHeight: 48,
    width: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  descriptionInput: {
    minHeight: 88,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    lineHeight: 22,
  },
  characterCount: { textAlign: "right", fontSize: 13, lineHeight: 19 },
  actions: { flexDirection: "row", gap: 12, paddingTop: 2 },
  cancelButton: {
    minHeight: 50,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButton: {
    flex: 1,
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  textButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  buttonText: { fontSize: 14, lineHeight: 22, fontWeight: "600" },
});
