import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  content: {
    paddingHorizontal: 22,
    paddingBottom: 40,
    width: "100%",
    maxWidth: 680,
    alignSelf: "center",
  },
  intro: { paddingTop: 4, paddingBottom: 20 },
  profileLabel: { fontSize: 15, lineHeight: 22, fontWeight: "600" },
  profileTags: { fontSize: 14, lineHeight: 21 },
  interestButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  interestButtonText: { fontSize: 14, lineHeight: 21, fontWeight: "600" },
  eyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  previewBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 7,
  },
  eyebrow: { fontSize: 12, fontWeight: "600", lineHeight: 18 },
  hero: {
    fontSize: 28,
    lineHeight: 38,
    fontWeight: "600",
    letterSpacing: -0.7,
    marginTop: 20,
  },
  description: { fontSize: 14, lineHeight: 22, marginTop: 10 },
  caption: { fontSize: 12, lineHeight: 18 },
  searchBox: {
    borderWidth: 1,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 14,
    paddingRight: 6,
    paddingVertical: 6,
    gap: 4,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    maxHeight: 110,
    fontSize: 15,
    lineHeight: 22,
    paddingHorizontal: 7,
    paddingVertical: 12,
  },
  iconButton: {
    minHeight: 48,
    width: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  searchButton: {
    minHeight: 48,
    width: 48,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  keywordSection: { marginTop: 18, gap: 8 },
  sectionLabel: { fontSize: 12, fontWeight: "500", lineHeight: 18 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  exampleChip: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 16,
    justifyContent: "center",
  },
  chipText: { fontSize: 14, fontWeight: "500", lineHeight: 20 },
  savedChip: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 14,
    maxWidth: "100%",
  },
  savedChipLabel: {
    paddingLeft: 14,
    paddingVertical: 10,
    minHeight: 48,
    justifyContent: "center",
    flexShrink: 1,
  },
  errorText: { fontSize: 13, lineHeight: 20, marginTop: 12 },
  emptyState: {
    alignItems: "center",
    paddingTop: 44,
    paddingBottom: 36,
    paddingHorizontal: 10,
  },
  emptyIcon: {
    height: 68,
    width: 68,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 17,
  },
  emptyTitle: {
    fontSize: 17,
    lineHeight: 26,
    fontWeight: "600",
    textAlign: "center",
  },
  emptyBody: {
    fontSize: 14,
    lineHeight: 23,
    textAlign: "center",
    marginTop: 8,
  },
  results: { marginTop: 30 },
  resultHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  resultTitle: {
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 29,
    letterSpacing: -0.4,
    flex: 1,
  },
  resultCount: { fontSize: 12, lineHeight: 29 },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minHeight: 48,
    alignSelf: "flex-start",
    marginBottom: 5,
  },
  saveText: { fontSize: 13, lineHeight: 20, fontWeight: "500" },
  mailList: { borderRadius: 18, borderWidth: 1, overflow: "hidden" },
  mailRow: { padding: 18 },
  senderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  sender: { fontSize: 12, fontWeight: "500", lineHeight: 20, flexShrink: 1 },
  mailTitle: {
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 25,
    letterSpacing: -0.3,
    marginTop: 8,
  },
  mailPreview: { fontSize: 14, lineHeight: 22, marginTop: 6 },
  messageFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  topicText: { fontSize: 12, fontWeight: "500", lineHeight: 18 },
  importanceBadge: {
    alignSelf: "flex-start",
    borderRadius: 6,
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  detailHeading: { flex: 1, alignItems: "flex-start" },
  noResults: {
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 30,
    gap: 9,
    alignItems: "center",
  },
  previewNote: {
    textAlign: "center",
    fontSize: 12,
    lineHeight: 20,
    marginTop: 24,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.35)",
  },
  modalDismiss: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
  detailSheet: {
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    maxHeight: "85%",
    width: "100%",
    maxWidth: 680,
    alignSelf: "center",
    overflow: "hidden",
  },
  detailHeader: {
    paddingHorizontal: 24,
    paddingTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  detailContent: { paddingHorizontal: 24, paddingBottom: 36 },
  detailTitle: {
    fontSize: 23,
    fontWeight: "600",
    lineHeight: 34,
    letterSpacing: -0.4,
    marginTop: 10,
  },
  detailSender: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 20,
    borderBottomWidth: 1,
    marginBottom: 24,
  },
  senderIcon: {
    height: 42,
    width: 42,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  senderCopy: { flex: 1, gap: 3 },
  detailBody: { fontSize: 15, lineHeight: 27 },
});
