import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  actionCard: { borderRadius: 15, borderWidth: 1, marginTop: 12, padding: 13 },
  actionCopy: { flex: 1, minWidth: 0 },
  actionIndex: {
    alignItems: "center",
    borderRadius: 10,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  actionIndexText: { fontSize: 12, fontWeight: "600" },
  actionStatus: {
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 8,
  },
  actionTarget: { fontSize: 13, lineHeight: 19, marginTop: 4 },
  actionTitle: { fontSize: 15, fontWeight: "600", lineHeight: 22 },
  actionTop: { alignItems: "flex-start", flexDirection: "row", gap: 9 },
  approvalBody: { fontSize: 14, lineHeight: 21, marginTop: 6 },
  approvalCard: {
    borderRadius: 19,
    borderWidth: 1,
    marginTop: 18,
    padding: 18,
  },
  approvalEyebrow: { fontSize: 10, fontWeight: "600", letterSpacing: 0.4 },
  approvalTitle: { fontSize: 18, fontWeight: "600", lineHeight: 26 },
  approveButton: {
    alignItems: "center",
    borderRadius: 14,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginTop: 14,
    minHeight: 50,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  approveText: {
    flexShrink: 1,
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 23,
    textAlign: "center",
  },
  bubble: {
    borderRadius: 14,
    marginTop: 9,
    maxWidth: "88%",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  bubbleText: { fontSize: 14, lineHeight: 21 },
  buttonRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  card: { borderRadius: 18, borderWidth: 1, padding: 16 },
  cardDivider: { height: StyleSheet.hairlineWidth, marginVertical: 13 },
  caseType: {
    flexShrink: 1,
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 18,
    marginLeft: "auto",
  },
  changeCard: { borderRadius: 18, marginTop: 20, padding: 15 },
  changeReason: { fontSize: 14, lineHeight: 21, marginTop: 8 },
  changeTitle: { flex: 1, fontSize: 15, fontWeight: "600", lineHeight: 22 },
  changeTitleRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  chatComposer: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  chatInput: {
    borderRadius: 13,
    borderWidth: 1,
    flex: 1,
    fontSize: 14,
    maxHeight: 120,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  chatNote: { fontSize: 13, lineHeight: 20 },
  content: { padding: 20, paddingBottom: 38, paddingTop: 12 },
  disclosure: {
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 14,
    overflow: "hidden",
  },
  disclosureBody: {
    borderTopWidth: StyleSheet.hairlineWidth,
    padding: 14,
  },
  disclosureCount: { fontSize: 12, fontWeight: "600", lineHeight: 18 },
  disclosureHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
    minHeight: 58,
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  disclosureIcon: {
    alignItems: "center",
    borderRadius: 12,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  disclosureTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 23,
  },
  diff: {
    borderRadius: 12,
    flex: 1,
    minWidth: 120,
    minHeight: 74,
    padding: 12,
  },
  diffLabel: { fontSize: 12, fontWeight: "600", lineHeight: 18 },
  diffRow: {
    flexWrap: "wrap",
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
    marginTop: 12,
  },
  diffText: { fontSize: 13, lineHeight: 20, marginTop: 5 },
  errorCard: {
    alignItems: "flex-start",
    borderRadius: 14,
    flexDirection: "row",
    gap: 9,
    marginTop: 12,
    padding: 13,
  },
  errorText: { flex: 1, fontSize: 14, lineHeight: 21 },
  evidenceCopy: { flex: 1, minWidth: 0 },
  evidenceItem: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingTop: 8,
    paddingBottom: 12,
    marginBottom: 8,
  },
  evidenceRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    marginVertical: 6,
  },
  evidenceText: { fontSize: 14, lineHeight: 21, marginTop: 4 },
  evidenceTitle: { fontSize: 14, fontWeight: "600", lineHeight: 21 },
  executionBody: { fontSize: 14, lineHeight: 21, marginTop: 4 },
  executionCard: {
    alignItems: "center",
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginTop: 15,
    padding: 14,
  },
  executionTitle: { fontSize: 16, fontWeight: "600", lineHeight: 24 },
  executionNext: { fontSize: 13, lineHeight: 21, marginTop: 10 },
  completionCard: {
    borderRadius: 17,
    borderWidth: 1,
    marginTop: 15,
    padding: 16,
  },
  failureCard: { borderRadius: 18, marginTop: 20, padding: 15 },
  failureCount: { alignItems: "center", flex: 1, minWidth: 72 },
  failureCounts: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 13,
  },
  failureLabel: {
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 2,
    textAlign: "center",
  },
  failureValue: { fontSize: 18, fontWeight: "600" },
  grant: {
    minHeight: 60,
    alignItems: "flex-start",
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    padding: 11,
  },
  grantBody: { fontSize: 13, lineHeight: 20, marginTop: 3 },
  grantCopy: { flex: 1 },
  grantTitle: { fontSize: 14, fontWeight: "600", lineHeight: 21 },
  grants: { gap: 8, marginTop: 14 },
  hashLabel: { fontSize: 8, fontWeight: "600", letterSpacing: 0.5 },
  hashRow: {
    alignItems: "center",
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  hashValue: {
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace" }),
    fontSize: 9,
  },
  metaLabel: { fontSize: 12, fontWeight: "600", lineHeight: 18 },
  metaLine: { alignItems: "flex-start", flexDirection: "row", gap: 9 },
  metaValue: { fontSize: 14, lineHeight: 21, marginTop: 3 },
  nextCard: {
    alignItems: "flex-start",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: 15,
    padding: 13,
  },
  nextCopy: { flex: 1, minWidth: 0 },
  nextLabel: { fontSize: 12, fontWeight: "600" },
  nextValue: { fontSize: 14, fontWeight: "400", lineHeight: 21, marginTop: 4 },
  parameterKey: { fontSize: 12, fontWeight: "600", lineHeight: 18 },
  parameterRow: { gap: 3 },
  parameterRows: { gap: 10, marginTop: 12 },
  parameterValue: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 21,
    flexShrink: 1,
  },
  pills: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  planCopy: { flex: 1 },
  planContent: { padding: 0, paddingTop: 12 },
  planPreview: { paddingHorizontal: 16, paddingBottom: 17 },
  previewAction: { fontSize: 14, lineHeight: 22, marginTop: 6 },
  planHeader: { alignItems: "flex-start", flexDirection: "row", gap: 10 },
  planMeta: {
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: 11,
    marginTop: 14,
    paddingTop: 13,
  },
  planOutcome: { fontSize: 15, fontWeight: "600", lineHeight: 21 },
  planReason: { fontSize: 14, lineHeight: 21, marginTop: 6 },
  reconnectBody: { fontSize: 14, lineHeight: 21, marginTop: 5 },
  reconnectCard: { borderRadius: 17, marginTop: 16, padding: 15 },
  reconnectTitle: { fontSize: 13, fontWeight: "600" },
  resultText: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 21,
    marginTop: 10,
  },
  retryButton: {
    alignItems: "center",
    borderRadius: 13,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    marginTop: 13,
    minHeight: 48,
  },
  retryText: {
    color: "#fff",
    flexShrink: 1,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 22,
    textAlign: "center",
  },
  revision: { fontSize: 9, fontWeight: "600" },
  loading: { marginVertical: 32 },
  recoveryCard: {
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 16,
    padding: 16,
  },
  recoveryTitle: { fontSize: 16, fontWeight: "600", lineHeight: 24 },
  recoveryBody: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 21,
    marginTop: 6,
  },
  screen: { flex: 1 },
  secondaryButton: {
    minWidth: 120,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 13,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
  },
  secondaryText: {
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
    textAlign: "center",
  },
  sendButton: {
    alignItems: "center",
    borderRadius: 13,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  stopButton: {
    alignItems: "center",
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: "center",
    marginTop: 22,
    minHeight: 48,
  },
  stopText: {
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 22,
    textAlign: "center",
  },
  summary: { fontSize: 14, lineHeight: 21, marginTop: 8 },
  timelineBody: { fontSize: 14, lineHeight: 21, marginTop: 4 },
  timelineCopy: { flex: 1, paddingBottom: 19 },
  timelineDot: { borderRadius: 5, height: 10, marginTop: 4, width: 10 },
  timelineLine: { flex: 1, marginVertical: 5, width: 1 },
  timelineRail: { alignItems: "center", width: 12 },
  timelineRow: { flexDirection: "row", gap: 12 },
  timelineTime: { fontSize: 12, lineHeight: 18, marginTop: 5 },
  timelineTitle: { fontSize: 14, fontWeight: "600", lineHeight: 22 },
  title: {
    fontSize: 24,
    fontWeight: "600",
    letterSpacing: -0.6,
    lineHeight: 34,
    marginTop: 13,
  },
  versionBadge: { borderRadius: 9, paddingHorizontal: 8, paddingVertical: 6 },
  versionText: { fontSize: 9, fontWeight: "600" },
  whyNow: { fontSize: 14, fontWeight: "400", lineHeight: 21 },
  overview: { borderRadius: 20, borderWidth: 1, padding: 18 },
  scenarioNote: { fontSize: 12, lineHeight: 19, marginTop: 12 },
  reasonSection: { gap: 7, marginTop: 25, paddingHorizontal: 2 },
  sectionLabel: { fontSize: 16, fontWeight: "600", lineHeight: 24 },
  refreshing: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  refreshingText: { flex: 1, fontSize: 13, lineHeight: 20 },
  inlineDisclosure: {
    alignItems: "center",
    alignSelf: "flex-start",
    flexDirection: "row",
    gap: 5,
    minHeight: 48,
    paddingVertical: 10,
  },
  inlineDisclosureText: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
  },
  originalBox: { borderRadius: 12, gap: 8, padding: 12 },
  originalText: { fontSize: 13, lineHeight: 21 },
  originalMeta: { fontSize: 12, lineHeight: 19 },
});
