import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  actionBody: { fontSize: 14, lineHeight: 21, marginTop: 5 },
  actionCopy: { flex: 1, minWidth: 0 },
  actionMeta: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginTop: 10,
  },
  actionRow: {
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 12,
    minHeight: 88,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  actionTime: { fontSize: 12, lineHeight: 18, marginLeft: "auto" },
  actionTitle: {
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: -0.25,
    lineHeight: 24,
  },
  clearSearchButton: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
    minWidth: 48,
  },
  composer: {
    alignItems: "center",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    padding: 6,
  },
  composerDock: {
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingBottom: 9,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  composerInput: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    maxHeight: 96,
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  content: { paddingBottom: 28, paddingHorizontal: 20 },
  errorRow: {
    alignItems: "flex-start",
    borderRadius: 14,
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
    padding: 14,
  },
  errorText: { flex: 1, fontSize: 14, lineHeight: 21 },
  filter: {
    alignItems: "center",
    borderRadius: 14,
    flexDirection: "row",
    gap: 7,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  filterCount: {
    alignItems: "center",
    borderRadius: 8,
    justifyContent: "center",
    minHeight: 20,
    minWidth: 20,
    paddingHorizontal: 5,
  },
  filterCountText: { fontSize: 11, fontWeight: "600" },
  filterText: { fontSize: 13, fontWeight: "600" },
  filters: { gap: 4, paddingBottom: 12 },
  loading: { marginVertical: 40 },
  mailFocusEntry: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 15,
    borderWidth: 1,
    borderRadius: 17,
    marginBottom: 16,
  },
  mailFocusCopy: { flex: 1, gap: 3 },
  mailFocusTitle: { fontSize: 15, fontWeight: "600", lineHeight: 22 },
  mailFocusBody: { fontSize: 12, lineHeight: 19 },
  moreButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 12,
  },
  moreText: { fontSize: 13, fontWeight: "600" },
  priorityDot: { borderRadius: 3, height: 6, width: 6 },
  relatedCount: { fontSize: 12, lineHeight: 18 },
  retryButton: {
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 48,
    minWidth: 78,
    paddingHorizontal: 12,
  },
  retryText: { fontSize: 13, fontWeight: "600" },
  screen: { flex: 1 },
  searchBox: {
    alignItems: "center",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
    paddingLeft: 14,
    paddingRight: 4,
  },
  searchInput: { flex: 1, fontSize: 15, minHeight: 48 },
  sections: { gap: 16 },
  sendButton: {
    alignItems: "center",
    borderRadius: 14,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  sourceChevron: { marginLeft: "auto" },
  sourceHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  sourceHeaderMain: { flex: 1, minWidth: 100 },
  sourceCount: { fontSize: 13, fontWeight: "500" },
  sourceHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    minHeight: 48,
    paddingHorizontal: 3,
    paddingVertical: 6,
  },
  sourceLabel: { fontSize: 15, fontWeight: "600" },
  sourceProgressFill: { borderRadius: 999, height: 4 },
  sourceProgressTrack: { borderRadius: 999, height: 4, marginTop: 8 },
  sourceRows: {
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: "hidden",
  },
  sourceStatusBadge: {
    borderRadius: 8,
    marginLeft: "auto",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  sourceStatusBadgeText: { fontSize: 11, fontWeight: "600" },
  sourceStatusBody: { fontSize: 13, lineHeight: 20 },
  sourceStatusCopy: { flex: 1 },
  sourceStatusRow: {
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  stanceText: { fontSize: 12, fontWeight: "500", lineHeight: 18 },
});
